// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	models "github.com/Arif9878/stockbit-test/question-2/models"
	mock "github.com/stretchr/testify/mock"
)

// ImdbRepository is an autogenerated mock type for the ImdbRepository type
type ImdbRepository struct {
	mock.Mock
}

// FetchList provides a mock function with given fields: query
func (_m *ImdbRepository) FetchList(query *models.QueryParams) (*models.SearchResponse, error) {
	ret := _m.Called(query)

	var r0 *models.SearchResponse
	if rf, ok := ret.Get(0).(func(*models.QueryParams) *models.SearchResponse); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SearchResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*models.QueryParams) error); ok {
		r1 = rf(query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ID
func (_m *ImdbRepository) GetByID(ID string) (*models.MovieDetail, error) {
	ret := _m.Called(ID)

	var r0 *models.MovieDetail
	if rf, ok := ret.Get(0).(func(string) *models.MovieDetail); ok {
		r0 = rf(ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.MovieDetail)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
